name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt; 
          fi

      - name: Run Bookbot on Frankenstein
        run: python main.py books/frankenstein.txt

      - name: Run Bookbot on Mobydick
        run: python main.py books/mobydick.txt

      - name: Run Bookbot on Pride and Prejudice
        run: python main.py books/prideandprejudice.txt
