name: BookBot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov

      - name: Run Pylint
        run: |
          # Run pylint on all Python files (adjust the paths as needed)
          pylint main.py stats.py

      - name: Run unit tests with coverage
        run: pytest --cov=. --cov-report=xml

      - name: Smoke test on Frankenstein
        run: python main.py books/frankenstein.txt

      - name: Smoke test on Mobydick
        run: python main.py books/mobydick.txt

      - name: Smoke test on Pride and Prejudice
        run: python main.py books/prideandprejudice.txt
